import { useEffect, useState } from 'react'
import { adminApi, downloadReport } from './api'
import { Button, Card, Empty, Field, Loading, Modal, Notice, fmtDate, useSubmit } from './ui'

function useList(path){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=()=>{setLoading(true);adminApi(path).then(d=>setRows(d.results||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[path]);return{rows,loading,error,load}}

export function CategoriesTab({csrfToken}){const list=useList('/categories'),[editing,setEditing]=useState(null);return <><Card title="หมวดหมู่อันดับ"><Notice>{list.error}</Notice>{list.loading?<Loading/>:<div className="admin-table-wrap"><table><thead><tr><th>หมวดหมู่</th><th>Slug</th><th>ลำดับ</th><th>สถานะ</th><th/></tr></thead><tbody>{list.rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.description}</small></td><td>{r.slug}</td><td>{r.sort_order}</td><td>{r.status}</td><td><button onClick={()=>setEditing(r)}>แก้ไข</button></td></tr>)}</tbody></table></div>}</Card>{editing&&<CategoryForm value={editing} csrfToken={csrfToken} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);list.load()}}/>}</>}
function CategoryForm({value,csrfToken,onClose,onSaved}){const [form,setForm]=useState(value);const save=useSubmit(()=>adminApi(`/categories/${value.id}`,{method:'PUT',body:form,csrfToken}),onSaved);return <Modal title="แก้ไขหมวดหมู่" onClose={onClose}><form onSubmit={save.submit}><Notice>{save.error}</Notice><div className="admin-grid"><Field label="ชื่อ"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Slug"><input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></Field><Field label="ลำดับ"><input type="number" required value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></Field><Field label="สถานะ"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select></Field><Field label="คำอธิบาย" wide><textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div><Button className="primary" busy={save.busy}>บันทึก</Button></form></Modal>}

export function ReportsTab({csrfToken}){const list=useList('/reports'),now=new Date(),[form,setForm]=useState({period:'monthly',month:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,category:'followers'}),[downloadError,setDownloadError]=useState('');const save=useSubmit(()=>adminApi('/reports',{method:'POST',body:form,csrfToken}),list.load);const download=async id=>{setDownloadError('');try{await downloadReport(id,csrfToken)}catch(e){setDownloadError(e.message)}};return <Card title="รายงาน"><form className="toolbar" onSubmit={save.submit}><Field label="ช่วงเวลา"><select value={form.period} onChange={e=>setForm({...form,period:e.target.value})}><option value="monthly">รายเดือน</option><option value="alltime">ตลอดกาล</option></select></Field>{form.period==='monthly'&&<Field label="เดือน"><input type="month" required value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></Field>}<Field label="ตัวชี้วัด"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="followers">ผู้ติดตาม</option><option value="views">ยอดดู</option><option value="videos">จำนวนคลิป</option></select></Field><Button className="primary" busy={save.busy}>สร้างรายงาน</Button></form><Notice>{list.error||save.error||downloadError}</Notice>{list.loading?<Loading/>:list.rows.length?<div className="admin-table-wrap"><table><thead><tr><th>รายงาน</th><th>จำนวนช่อง</th><th>สร้างเมื่อ</th><th/></tr></thead><tbody>{list.rows.map(r=><tr key={r.id}><td><strong>{r.report_type||r.category_id}</strong><small>{r.report_period}</small></td><td>{r.total_vtubers}</td><td>{fmtDate(r.generated_at)}</td><td><button onClick={()=>download(r.id)}>ดาวน์โหลด CSV</button></td></tr>)}</tbody></table></div>:<Empty/>}</Card>}

const blankUser={username:'',display_name:'',email:'',role:'staff',status:'active',password:''}
export function UsersTab({csrfToken,currentUser}){const list=useList('/users'),[editing,setEditing]=useState(null);return <><Card title="ผู้ใช้งาน" actions={<button className="primary" onClick={()=>setEditing({...blankUser})}>เพิ่มผู้ใช้</button>}><Notice>{list.error}</Notice>{list.loading?<Loading/>:<div className="admin-table-wrap"><table><thead><tr><th>ผู้ใช้</th><th>สิทธิ์</th><th>สถานะ</th><th>เข้าล่าสุด</th><th/></tr></thead><tbody>{list.rows.map(r=><tr key={r.id}><td><strong>{r.display_name}</strong><small>@{r.username} · {r.email}</small></td><td>{r.role}</td><td>{r.status}</td><td>{fmtDate(r.last_login_at)}</td><td><button onClick={()=>setEditing({...r,password:''})}>แก้ไข</button>{r.id!==currentUser.id&&r.status==='active'&&<QuickDisable row={r} csrfToken={csrfToken} done={list.load}/>}</td></tr>)}</tbody></table></div>}</Card>{editing&&<UserForm value={editing} csrfToken={csrfToken} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);list.load()}}/>}</>}
function QuickDisable({row,csrfToken,done}){const save=useSubmit(()=>adminApi(`/users/${row.id}`,{method:'PUT',csrfToken,body:{display_name:row.display_name,email:row.email,role:row.role,status:'inactive'}}),done);return <button className="danger" disabled={save.busy} onClick={save.submit}>ปิดใช้งาน</button>}
function UserForm({value,csrfToken,onClose,onSaved}){const [form,setForm]=useState(value),isEdit=Boolean(value.id);const save=useSubmit(()=>adminApi(`/users${isEdit?`/${value.id}`:''}`,{method:isEdit?'PUT':'POST',csrfToken,body:form}),onSaved);return <Modal title={isEdit?'แก้ไขผู้ใช้':'เพิ่มผู้ใช้'} onClose={onClose}><form onSubmit={save.submit}><Notice>{save.error}</Notice><div className="admin-grid">{!isEdit&&<Field label="ชื่อผู้ใช้"><input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Field>}<Field label="ชื่อที่แสดง"><input required value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></Field><Field label="อีเมล"><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="สิทธิ์"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="staff">Staff</option><option value="manager">Manager</option></select></Field><Field label="สถานะ"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select></Field><Field label={isEdit?'รหัสผ่านใหม่ (ไม่บังคับ)':'รหัสผ่าน'}><input type="password" autoComplete="new-password" minLength="8" required={!isEdit} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field></div><Button className="primary" busy={save.busy}>บันทึก</Button></form></Modal>}

export function AuditTab(){const list=useList('/audit-logs');return <Card title="ประวัติการทำงาน"><Notice>{list.error}</Notice>{list.loading?<Loading/>:list.rows.length?<div className="admin-table-wrap"><table><thead><tr><th>เวลา</th><th>ผู้ใช้</th><th>การทำงาน</th><th>รายการ</th><th>รายละเอียด</th></tr></thead><tbody>{list.rows.map(r=><tr key={r.id}><td>{fmtDate(r.created_at)}</td><td>{r.display_name||r.username||r.user_id}</td><td>{r.action}</td><td>{r.target_type} {r.target_id}</td><td><small>{typeof r.details==='string'?r.details:JSON.stringify(r.details)}</small></td></tr>)}</tbody></table></div>:<Empty/>}</Card>}

export function SettingsTab({csrfToken}){const [form,setForm]=useState({site_name:'',site_status:'active',current_ranking_period:'',ranking_update_frequency:'manual'}),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false);useEffect(()=>{adminApi('/settings').then(d=>{setForm(d.settings||d);setLoaded(true)}).finally(()=>setLoading(false))},[]);const save=useSubmit(()=>adminApi('/settings',{method:'PUT',csrfToken,body:form}));return <Card title="ตั้งค่าเว็บไซต์">{loading?<Loading/>:<form onSubmit={save.submit}><Notice type={save.error?'error':'success'}>{save.error||(!save.busy&&loaded&&'')}</Notice><div className="admin-grid"><Field label="ชื่อเว็บไซต์"><input required value={form.site_name||''} onChange={e=>setForm({...form,site_name:e.target.value})}/></Field><Field label="สถานะเว็บไซต์"><select value={form.site_status} onChange={e=>setForm({...form,site_status:e.target.value})}><option value="active">เปิดใช้งาน</option><option value="maintenance">ปิดปรับปรุง</option></select></Field><Field label="เดือนอันดับปัจจุบัน"><input type="month" required value={form.current_ranking_period||''} onChange={e=>setForm({...form,current_ranking_period:e.target.value})}/></Field><Field label="ความถี่การอัปเดต"><select value={form.ranking_update_frequency} onChange={e=>setForm({...form,ranking_update_frequency:e.target.value})}><option value="manual">ด้วยตนเอง</option><option value="monthly">รายเดือน</option></select></Field></div><Button className="primary" busy={save.busy}>บันทึกการตั้งค่า</Button></form>}</Card>}
