import { useEffect, useState } from 'react'
import { adminApi } from './api'
import { Button, Card, Empty, Field, Loading, Notice, fmtNumber, useSubmit } from './ui'

export default function RankingsTab({csrfToken,isManager}){
 const now=new Date(), [filters,setFilters]=useState({period:'monthly',month:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,category:'followers'}),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const load=()=>{setLoading(true);setError('');adminApi(`/rankings?${new URLSearchParams(filters)}`).then(d=>setRows(d.results||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[filters.period,filters.month,filters.category])
 const calc=useSubmit(()=>adminApi('/rankings/calculate',{method:'POST',body:filters,csrfToken}),load)
 return <Card title="อันดับ"><div className="toolbar"><Field label="ช่วงเวลา"><select value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}><option value="monthly">รายเดือน</option><option value="alltime">ตลอดกาล</option></select></Field>{filters.period==='monthly'&&<Field label="เดือน"><input type="month" value={filters.month} onChange={e=>setFilters({...filters,month:e.target.value})}/></Field>}<Field label="ตัวชี้วัด"><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="followers">ผู้ติดตาม</option><option value="views">ยอดดู</option><option value="videos">จำนวนคลิป</option></select></Field>{isManager&&<Button className="primary" busy={calc.busy} onClick={calc.submit}>คำนวณอันดับใหม่</Button>}</div><Notice>{error||calc.error}</Notice>{loading?<Loading/>:rows.length?<div className="admin-table-wrap"><table><thead><tr><th>อันดับ</th><th>ช่อง</th><th>คะแนน</th><th>เปลี่ยนแปลง</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||`${r.vtuber_id}-${i}`}><td><strong>#{r.rank}</strong></td><td>{r.name||r.vtuber_name}</td><td>{fmtNumber(filters.category==='followers'?(r.subscriber_count??r.followers):filters.category==='videos'?(r.video_count??0):r.total_views)}</td><td>{r.rank_change>0?`+${r.rank_change}`:r.rank_change??'—'}</td></tr>)}</tbody></table></div>:<Empty>ยังไม่มีอันดับสำหรับช่วงเวลานี้</Empty>}</Card>
}
