name = "vtuberthai-updater"
main = "updater.js"
compatibility_date = "2026-09-15"

[secrets]
required = ["YOUTUBE_API_KEY", "UPDATER_RUN_TOKEN"]

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vtuberthai-db"
database_id = "9585907e-612d-4cc3-84b4-f75a41690989"
